### PR TITLE
QuickSwap (Polygon)

### PR DESCRIPTION
**Pull request by NelsonGaldeman**

### CODE REVIEW

**Comment by gvladika** [comment]
When dealing with forks, I think nicer approach would be using manifest templating instead of c/p whole codebase. Only a small config is needed and we avoid duplication. I used that approach for Aave multi-chain deployment and it was quite convenient. What do you think?

**Comment by tarunbhm** [comment]
@gvladika yea you are right, I also read about it but it seemed tough to setup and get working so I did not invest much time in it. Agreed that it's better approach then having duplicate code. In case we need to develop custom logic for a specific network then we can create a new folder for this specific case.

**Comment by NelsonGaldeman** [comment]
> When dealing with forks, I think nicer approach would be using manifest templating instead of c/p whole codebase. Only a small config is needed and we avoid duplication. I used that approach for Aave multi-chain deployment and it was quite convenient. What do you think?

I agree! I'll update it to be within uni subgraph. 

I followed the Sushi pattern where we duplicated the code because it's a different DEX. But the less repetition the better, specially when we have to fix stuff!

**Comment by NelsonGaldeman** [comment]
Closing this off, see #22

**Pull request closed without merging**
