### PR TITLE
Catch uniswapv2 forks

### PR DESCRIPTION
**Pull request by gvladika**

### CODE REVIEW

**Comment by tarunbhm** [comment]
@gvladika can you also add new subgraph deploy commands in `deploy-all` command as well? Thanks

**Comment by gvladika** [comment]
> @gvladika can you also add new subgraph deploy commands in `deploy-all` command as well? Thanks

ah yes, will do it. 
btw. for now I deployed new subgraphs under my account - because I can't deploy under simplefi and because I wanted to make sure syncing works fine on these exotic chains. Once they are deployed I think it's easy to just switch account/names to simplefi standard

**Comment by tarunbhm** [comment]
> > @gvladika can you also add new subgraph deploy commands in `deploy-all` command as well? Thanks
> 
> ah yes, will do it. btw. for now I deployed new subgraphs under my account - because I can't deploy under simplefi and because I wanted to make sure syncing works fine on these exotic chains. Once they are deployed I think it's easy to just switch account/names to simplefi standard

Yea, agreed. We can deploy them to simplfi account when we make them bug free and are sure that other chain syncing is working fine

**Comment by NelsonGaldeman** [comment]
Found AuroraSwap and added it. It's quite new the factory was deployed less than a month ago!

**Pull request merged**
